
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '<your-azure-subscription>'
  appName: '<your-azure-function-app-name>'
  resourceGroup: '<your-resource-group>'

jobs:
- job: build_and_deploy
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - checkout: self
  - task: InstallPythonDependencies@0
    inputs:
      requirementsFile: 'azure-function/requirements.txt'
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: 'azure-function'
